In [1]:
import torch
from torch import nn

#### **Linear**

In [11]:
x = torch.randn(8,10)
# Input has 10 featuresand having 8 batches of data
linear = nn.Linear(10,5)    # output neurons having 5 nuerons
out = linear(x)

In [12]:
out

tensor([[ 1.3956, -0.4068,  0.9135, -0.0567,  0.9425],
        [-0.8554, -0.9520, -0.2841,  0.2607, -0.6184],
        [-0.5602, -0.9550, -0.3731,  1.2849, -0.6647],
        [-0.1775, -0.9988,  0.3462,  0.2733, -0.1629],
        [ 0.3603, -0.3107, -0.4232,  0.4069,  0.1865],
        [ 0.0688,  0.3131, -0.2657, -0.1323,  0.2565],
        [ 0.2997, -0.8352, -1.2354, -0.1023,  0.2207],
        [ 0.5137, -0.0872, -0.4194, -0.7475,  0.1167]],
       grad_fn=<AddmmBackward0>)

#### **Convolution 2d**

In [74]:
# Reflection padding
a = torch.randn(1,4,3)
ref = nn.ReflectionPad2d((2,2,3,3))
a

tensor([[[-0.3197,  0.0570,  0.6016],
         [-1.4133, -0.8639, -1.8923],
         [-0.3725,  1.0006, -0.0581],
         [-0.5921,  0.1202, -0.3505]]])

In [75]:
ref(a)

tensor([[[-0.3505,  0.1202, -0.5921,  0.1202, -0.3505,  0.1202, -0.5921],
         [-0.0581,  1.0006, -0.3725,  1.0006, -0.0581,  1.0006, -0.3725],
         [-1.8923, -0.8639, -1.4133, -0.8639, -1.8923, -0.8639, -1.4133],
         [ 0.6016,  0.0570, -0.3197,  0.0570,  0.6016,  0.0570, -0.3197],
         [-1.8923, -0.8639, -1.4133, -0.8639, -1.8923, -0.8639, -1.4133],
         [-0.0581,  1.0006, -0.3725,  1.0006, -0.0581,  1.0006, -0.3725],
         [-0.3505,  0.1202, -0.5921,  0.1202, -0.3505,  0.1202, -0.5921],
         [-0.0581,  1.0006, -0.3725,  1.0006, -0.0581,  1.0006, -0.3725],
         [-1.8923, -0.8639, -1.4133, -0.8639, -1.8923, -0.8639, -1.4133],
         [ 0.6016,  0.0570, -0.3197,  0.0570,  0.6016,  0.0570, -0.3197]]])

In [38]:
img = torch.randn(8,7,50,80)
# Input image having (5,8) size and 3 channels => 8 batches
conv = nn.Sequential(
    nn.ReflectionPad2d(1),
    nn.Conv2d(7,5,kernel_size=3,stride=1,padding='same')        # Output have 5 neurons
)
out = conv(img) 

In [39]:
out.shape

torch.Size([8, 5, 52, 82])

In [36]:
x = torch.rand(1,3,5,5)
conv = nn.Linear(5,2,bias=False)

In [37]:
x

tensor([[[[0.6413, 0.2258, 0.4779, 0.1451, 0.9165],
          [0.1236, 0.5681, 0.6454, 0.1888, 0.8771],
          [0.3584, 0.4388, 0.9393, 0.8606, 0.2602],
          [0.8578, 0.3752, 0.6422, 0.9536, 0.7200],
          [0.6745, 0.3448, 0.8279, 0.3713, 0.9421]],

         [[0.4812, 0.0567, 0.8137, 0.6545, 0.1797],
          [0.4372, 0.7834, 0.2818, 0.4584, 0.3356],
          [0.7850, 0.1500, 0.4659, 0.1379, 0.8142],
          [0.2499, 0.2721, 0.3901, 0.1910, 0.6858],
          [0.4856, 0.8548, 0.0078, 0.2662, 0.0158]],

         [[0.4157, 0.2377, 0.6009, 0.4433, 0.9976],
          [0.9837, 0.2083, 0.6957, 0.6463, 0.2669],
          [0.8079, 0.1897, 0.6943, 0.5660, 0.0227],
          [0.8183, 0.6001, 0.3676, 0.1246, 0.4724],
          [0.7240, 0.1267, 0.1056, 0.4477, 0.3011]]]])

In [38]:
out = conv(x)
out

tensor([[[[ 0.2206, -0.1298],
          [ 0.0456, -0.0015],
          [-0.0375,  0.0901],
          [ 0.1046, -0.1375],
          [ 0.1895, -0.0751]],

         [[ 0.0181, -0.0013],
          [ 0.1638,  0.1866],
          [ 0.2790, -0.1099],
          [ 0.0576, -0.0901],
          [ 0.2728,  0.3348]],

         [[ 0.0287, -0.2256],
          [ 0.2572,  0.0579],
          [ 0.2185,  0.1431],
          [ 0.3947,  0.1928],
          [ 0.1794, -0.0772]]]], grad_fn=<UnsafeViewBackward0>)

In [40]:
w = conv.state_dict()['weight']
# b = conv.state_dict()['bias']

In [41]:
w

tensor([[ 0.4350,  0.1700,  0.0177, -0.3109, -0.0655],
        [ 0.0968,  0.4170,  0.1884, -0.2413, -0.3721]])

In [43]:
x @ w.T

tensor([[[[ 0.2206, -0.1298],
          [ 0.0456, -0.0015],
          [-0.0375,  0.0901],
          [ 0.1046, -0.1375],
          [ 0.1895, -0.0751]],

         [[ 0.0181, -0.0013],
          [ 0.1638,  0.1866],
          [ 0.2790, -0.1099],
          [ 0.0576, -0.0901],
          [ 0.2728,  0.3348]],

         [[ 0.0287, -0.2256],
          [ 0.2572,  0.0579],
          [ 0.2185,  0.1431],
          [ 0.3947,  0.1928],
          [ 0.1794, -0.0772]]]])

In [1]:
import torch
from torch import nn

In [25]:
x = torch.randint(1,3,(4,2,2,2),dtype=torch.float32)
x


tensor([[[[2., 2.],
          [2., 1.]],

         [[2., 2.],
          [1., 1.]]],


        [[[2., 2.],
          [1., 1.]],

         [[1., 2.],
          [1., 1.]]],


        [[[2., 1.],
          [2., 1.]],

         [[2., 2.],
          [2., 1.]]],


        [[[2., 1.],
          [2., 2.]],

         [[1., 1.],
          [2., 2.]]]])

In [26]:
nn.BatchNorm2d(2,affine=True)(x)

tensor([[[[ 0.7746,  0.7746],
          [ 0.7746, -1.2910]],

         [[ 1.0000,  1.0000],
          [-1.0000, -1.0000]]],


        [[[ 0.7746,  0.7746],
          [-1.2910, -1.2910]],

         [[-1.0000,  1.0000],
          [-1.0000, -1.0000]]],


        [[[ 0.7746, -1.2910],
          [ 0.7746, -1.2910]],

         [[ 1.0000,  1.0000],
          [ 1.0000, -1.0000]]],


        [[[ 0.7746, -1.2910],
          [ 0.7746,  0.7746]],

         [[-1.0000, -1.0000],
          [ 1.0000,  1.0000]]]], grad_fn=<NativeBatchNormBackward0>)

In [22]:
torch.mean(x)

tensor(1.6250)

In [23]:
torch.var(x)

tensor(0.2679)

In [24]:
print((2-1.6250)/0.2679)

1.3997760358342664
