### **PyTorch**


#### **Tensors**
A tensor is a high dimensional vectors. It is generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

##### **Why Tensors**
Here are some reasons why tensors are preferred:

Efficient computations: Tensors are designed to efficiently handle computations involving multi-dimensional arrays, especially in large-scale applications. Libraries optimized for tensor operations can leverage hardware acceleration, such as GPUs or specialized tensor processing units (TPUs), to perform computations faster than numpy arrays.

Automatic differentiation: Tensors often come with built-in support for automatic differentiation, which is essential for training deep neural networks and optimizing complex mathematical models. This capability enables efficient computation of gradients, which are crucial in optimization algorithms like backpropagation.

Hardware compatibility: Tensors are compatible with specialized hardware architectures, such as GPUs, TPUs, and quantum processing units (QPUs), which can significantly speed up computations for certain applications. These hardware accelerators are designed to efficiently process tensors and can deliver substantial performance gains over traditional CPUs.

Quantum computing: Tensors are used in quantum computing frameworks like TensorFlow Quantum (TFQ) and PennyLane. These frameworks enable the integration of quantum circuits with classical machine learning models and provide tools for training and optimizing quantum circuits. Tensors allow for efficient representation and manipulation of quantum states, measurements, and operators.



In [1]:
import torch
import numpy as np
print(torch.__version__)

1.12.1


#### **Convert numpy to tensor**

In [39]:
x=np.array([[1,2,3,4],[0,9,2,0]])
y=torch.from_numpy(x)
print(y)

# Know the shape of tensor
shape = y.size()            # y.shape also gives shape 
print("Shape: {}".format(shape))
print("First Element: {}".format(y[0][0]))

tensor([[1, 2, 3, 4],
        [0, 9, 2, 0]], dtype=torch.int32)
Shape: torch.Size([2, 4])
First Element: 1


In [12]:
print(y[:,0:2])

tensor([[1, 2],
        [0, 9]], dtype=torch.int32)


In [13]:
y[:,2]

tensor([3, 2], dtype=torch.int32)

In [14]:
#  Disadvantage of from_numpy. The array and tensor uses the same memory location.
# Change of element in a tensor reflects the change in array
y[0][2]=100
x 

array([[  1,   2, 100,   4],
       [  0,   9,   2,   0]])

In [15]:
# To overcome this we use tensor
z=torch.tensor(x)
z

tensor([[  1,   2, 100,   4],
        [  0,   9,   2,   0]], dtype=torch.int32)

In [41]:
# Reshaping in torch
w = y.view(2,1,2,2)
w.view(torch.float16)

tensor([[[[5.9605e-08, 0.0000e+00, 1.1921e-07, 0.0000e+00],
          [1.7881e-07, 0.0000e+00, 2.3842e-07, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 5.3644e-07, 0.0000e+00],
          [1.1921e-07, 0.0000e+00, 0.0000e+00, 0.0000e+00]]]],
       dtype=torch.float16)

In [47]:
# Check data type
w.dtype

torch.int32

In [4]:
# Concatination of tensors
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[-1,2],[0,7]])
c=torch.tensor([[11,21],[3,4]])
concat_tensor=torch.cat([a,b,c],dim = 1)
concat_tensor

tensor([[ 1,  2, -1,  2, 11, 21],
        [ 3,  4,  0,  7,  3,  4]])

In [50]:
# ones
one = torch.ones(2,3)
print(one)
# zero
zero = torch.zeros(2,3)
print(zero)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    device = torch.device("cuda")
    # It has two procedures
    x=torch.ones(5,device=device)   # ---> 1
    a=a.to(device)                  # ---> 2
print(x)
print(a)

#### **Using random**

#### **Arithematic**

In [20]:
# adding two tensors
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([[[4,5,6],[0,9,1]]], dtype=torch.float)
print(a + b)

tensor([[[ 7.,  9., 11.],
         [ 3., 13.,  6.]]])


In [16]:
# summing up tensor
x = torch.tensor([[2,3,4],[3,4,5]])
x.sum(dim = 0)

tensor([5, 7, 9])

In [17]:
# Dot product
dot_product=a.dot(b)
dot_product

tensor(62.)

In [18]:
# Multiplication
a.mul(b)

tensor([12., 20., 30.])

In [22]:
tensor1=torch.tensor([[2,3],[8,0]])
tensor2=torch.tensor([[1,0,-1,0],[2,-3,0,0]])
torch.matmul(tensor1,tensor2) 
# tensor.mm(tensor1,tensor2) & tensor1 @ tensor2 gives same result as matrix multiplication

tensor([[ 8, -9, -2,  0],
        [ 8,  0, -8,  0]])

In [23]:
tensor1 @ tensor2

tensor([[ 8, -9, -2,  0],
        [ 8,  0, -8,  0]])

In [36]:
# Equal 
torch.equal(tensor1,tensor2)

False

In [1]:
import torch

# Define the parameters of the uniform distribution
low = 0
high = 10
shape = (5,)  # Example: Generate 5 samples

# Generate random samples from a uniform distribution
uniform_samples = torch.randint(0,11,(8,))
uniform_samples

tensor([8, 0, 7, 9, 8, 7, 6, 8])

In [2]:
a = torch.rand(20)
a

tensor([0.6976, 0.6577, 0.6855, 0.9345, 0.9312, 0.1336, 0.3420, 0.9478, 0.7107,
        0.1880, 0.7228, 0.6941, 0.1840, 0.6336, 0.7945, 0.0130, 0.3208, 0.1336,
        0.4418, 0.5005])

In [13]:
out = a.gather(-1,uniform_samples)
out

tensor([0.7107, 0.6976, 0.9478, 0.1880, 0.7107, 0.9478, 0.3420, 0.7107])

In [14]:
reshape = out.reshape(8,*(1,1,1))
reshape.shape

torch.Size([8, 1, 1, 1])

In [10]:
x = torch.rand(8,2,3,3)
reshape*x

tensor([[[[2.4003e-01, 4.8137e-01, 3.2150e-01],
          [1.8798e-02, 5.4820e-01, 4.3689e-01],
          [6.6130e-01, 6.3981e-01, 2.9848e-01]],

         [[9.8741e-02, 2.1560e-01, 1.4765e-01],
          [5.9240e-01, 2.4195e-01, 2.5344e-02],
          [6.8464e-01, 6.0285e-01, 6.5976e-01]]],


        [[[5.4840e-01, 5.2073e-01, 5.9881e-01],
          [5.6088e-01, 1.1937e-02, 1.4825e-01],
          [3.4975e-01, 4.2459e-01, 4.7161e-01]],

         [[4.9377e-01, 1.3950e-01, 1.6011e-01],
          [3.9418e-01, 5.0169e-01, 6.7091e-01],
          [3.4537e-01, 4.7111e-01, 8.6552e-02]]],


        [[[3.8379e-01, 7.8955e-02, 3.6815e-01],
          [2.5691e-01, 3.3868e-01, 1.4155e-01],
          [2.0601e-01, 7.9533e-02, 5.7876e-01]],

         [[4.2005e-01, 3.6125e-02, 2.7469e-01],
          [1.3643e-01, 8.8086e-01, 7.4608e-01],
          [4.6831e-01, 6.5996e-01, 4.4732e-01]]],


        [[[3.2185e-02, 1.0693e-01, 1.2142e-01],
          [1.1546e-01, 5.2338e-02, 1.8025e-02],
          [3.7666e-02,

In [14]:
import tensorflow as tf


In [ ]:
a = tf.random.uniform(minval=0,maxval=10,shape=())

In [50]:
batch_size = 8
out = tf.gather(a, t)
tf.reshape(out, [batch_size, 1, 1, 1])

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
np.cumprod(x)

array([ 1,  2,  6, 24])

In [3]:
from functools import partial


def power(a, b):
	return a**b


# partial functions
pow2 = partial(power, b=2)
pow4 = partial(power, b=4)
power_of_5 = partial(power, 5)

print(power(2, 3))
print(pow2(4))
print(pow4(3))
print(power_of_5(2))

print('Function used in partial function pow2 :', pow2.func)
print('Default keywords for pow2 :', pow2.keywords)
print('Default arguments for power_of_5 :', power_of_5.args)


8
16
81
25
Function used in partial function pow2 : <function power at 0x0000028C5CAD6B00>
Default keywords for pow2 : {'b': 2}
Default arguments for power_of_5 : (5,)


In [6]:
x = torch.rand(2,3,3)
y = torch.tensor([[[1]],[[2]]])
y.shape

torch.Size([2, 1, 1])

In [7]:
torch.hstack((x,y))

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 1 for tensor number 1 in the list.

In [31]:
x = torch.rand(1,2,2,6)
y = torch.rand(1,6)

In [33]:
y

tensor([[0.0460, 0.8391, 0.8419, 0.5433, 0.2567, 0.8239]])

In [32]:
x + y

tensor([[[[0.4184, 1.1622, 1.4038, 1.2493, 0.3959, 1.7287],
          [0.7246, 1.2494, 1.0523, 0.7158, 0.9759, 1.3661]],

         [[0.2490, 0.9657, 1.6965, 0.9665, 0.4984, 1.6890],
          [0.1820, 1.4850, 1.7123, 1.5111, 0.8565, 1.3170]]]])

In [23]:
y.shape

torch.Size([1, 6])

In [24]:
y

tensor([[0.9645, 0.2420, 0.5812, 0.0685, 0.1389, 0.3207]])

In [25]:
from torch import nn

In [27]:
z = nn.Linear(6,10)(y)

In [30]:
z[:,:,None,None].shape

torch.Size([1, 10, 1, 1])

In [20]:
x

tensor([[[[0.1083, 0.2939, 0.8936, 0.3931, 0.9973, 0.6533],
          [0.0097, 0.1256, 0.0123, 0.9587, 0.1785, 0.8416]],

         [[0.3275, 0.1388, 0.6699, 0.4605, 0.4057, 0.2284],
          [0.3631, 0.3007, 0.9718, 0.0126, 0.4485, 0.0169]]]])

In [21]:
x + y

tensor([[[[0.1764, 0.4936, 1.0353, 0.7609, 1.1759, 0.7988],
          [0.1618, 0.7361, 0.0273, 1.9294, 0.3775, 1.5512]],

         [[0.3956, 0.3385, 0.8116, 0.8282, 0.5843, 0.3739],
          [0.5152, 0.9113, 0.9868, 0.9832, 0.6476, 0.7265]]]])

In [36]:
class Neural:
    def __init__(self) -> None:
        self.l = nn.Linear(2,3)
        
    def forward(self,x):
        return self.l(x)

In [37]:
y = torch.rand(1,2)
y

tensor([[0.0652, 0.5334]])

In [39]:
n = Neural()
n.forward(y)

tensor([[ 0.1057, -0.5522,  0.0108]], grad_fn=<AddmmBackward0>)

In [1]:
import numpy as np
x = np.array([1,2,3,4])
np.append(0,x)

array([0, 1, 2, 3, 4])