In [9]:
import torch
from torch import nn

In [18]:
x = torch.rand(3,4)

In [30]:
l = nn.ModuleList([nn.Linear(4, 4) for i in range(10)])
m = nn.Sequential(l[0])
m.add(l[1])

AttributeError: 'Sequential' object has no attribute 'add'

#### **Convolution2d**

In [24]:
x = torch.randn(20,4,32,32)
conv = nn.Conv2d(4,32,kernel_size=3)

In [25]:
out = conv(x)
print(out.shape)

torch.Size([20, 32, 30, 30])


In [32]:
y = torch.randn(3,3,2,2)
y

tensor([[[[ 0.7824,  0.8557],
          [ 1.4665,  1.6203]],

         [[-1.1681, -0.1618],
          [-0.7300, -2.2272]],

         [[ 0.0684,  0.4227],
          [ 1.4472,  0.0936]]],


        [[[ 0.3067,  0.1790],
          [-2.4943,  0.5529]],

         [[-0.5870,  1.0884],
          [-0.6585, -0.9977]],

         [[-0.4037,  0.1839],
          [ 1.4215, -0.0563]]],


        [[[-0.4610,  0.7890],
          [ 0.1192, -1.4708]],

         [[ 0.2918,  1.3851],
          [-0.0274,  0.2397]],

         [[ 0.9137, -0.3378],
          [-0.4931, -0.7996]]]])

In [34]:
conv = nn.Conv2d(3,3,kernel_size=1)
nn.Identity()(y)

tensor([[[[ 0.7824,  0.8557],
          [ 1.4665,  1.6203]],

         [[-1.1681, -0.1618],
          [-0.7300, -2.2272]],

         [[ 0.0684,  0.4227],
          [ 1.4472,  0.0936]]],


        [[[ 0.3067,  0.1790],
          [-2.4943,  0.5529]],

         [[-0.5870,  1.0884],
          [-0.6585, -0.9977]],

         [[-0.4037,  0.1839],
          [ 1.4215, -0.0563]]],


        [[[-0.4610,  0.7890],
          [ 0.1192, -1.4708]],

         [[ 0.2918,  1.3851],
          [-0.0274,  0.2397]],

         [[ 0.9137, -0.3378],
          [-0.4931, -0.7996]]]])

In [38]:
a = torch.Tensor([[[1,2]]])
b = torch.Tensor([[3],[2]])
a+b

tensor([[[4., 5.],
         [3., 4.]]])

In [46]:
a1 = torch.Tensor([1,2,3])
a2 = torch.Tensor([1,2,3])
res = torch.cat((a1,a2),dim=-1)

In [47]:
res

tensor([1., 2., 3., 1., 2., 3.])

In [52]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Concatenate along the last dimension (dimension -1)
result = torch.cat((tensor1, tensor2),dim=-1)

print(result)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [57]:
tensor1[None,:]

tensor([[[1, 2],
         [3, 4]]])

In [ ]:
# Position Encoding
x =25
device = x.devi


In [13]:
input = torch.randn(2, 12, 10, 10)
# Separate 6 channels into 3 groups
# m = nn.GroupNorm(3, 6)
# Separate 6 channels into 6 groups (equivalent with InstanceNorm)
# m = nn.GroupNorm(6, 6)
# Put all 6 channels into a single group (equivalent with LayerNorm)
m = nn.GroupNorm(1, 12)
# Activating the module
output = m(input)

In [23]:
input[0][0]

tensor([[ 1.4282e-01, -8.9297e-01,  1.6769e-01,  9.1209e-02, -1.8033e-01,
          5.1848e-01, -1.8393e-01, -9.1947e-01,  4.8938e-01,  8.7808e-02],
        [-7.1632e-01, -7.6656e-02, -3.6821e-02, -8.0401e-01,  6.5570e-01,
          1.2206e-02,  7.9335e-01,  8.8404e-01,  5.0927e-06, -9.7527e-01],
        [-1.2649e+00,  9.6975e-01,  8.2400e-01,  1.3851e+00,  2.5481e-02,
          1.2066e+00, -1.5203e+00,  7.7815e-01, -1.5145e+00,  1.4440e+00],
        [-2.0199e+00,  6.0005e-02,  1.2282e+00,  8.4320e-01,  1.4218e+00,
         -5.7969e-01, -2.3008e-01,  2.3765e-01, -6.5817e-01,  3.5241e-01],
        [-8.3671e-01,  7.0779e-01, -3.1955e-01, -1.6714e+00, -1.3844e-01,
          2.6609e+00,  1.2938e+00, -4.8768e-01,  9.1378e-01, -6.1546e-01],
        [-6.6937e-02, -3.4550e-02,  1.6667e+00,  6.3910e-02,  1.2450e+00,
         -8.2502e-02,  6.0486e-01, -2.6574e-01,  4.7956e-01,  7.8662e-01],
        [-5.4048e-01,  2.4659e+00, -3.0121e+00,  1.2592e+00,  6.8575e-01,
         -1.0281e+00, -2.8913e-0

In [24]:
output[0][0]

tensor([[ 0.1632, -0.9332,  0.1895,  0.1085, -0.1789,  0.5608, -0.1827, -0.9613,
          0.5300,  0.1049],
        [-0.7463, -0.0691, -0.0270, -0.8391,  0.7061,  0.0249,  0.8518,  0.9478,
          0.0120, -1.0204],
        [-1.3270,  1.0385,  0.8842,  1.4781,  0.0390,  1.2892, -1.5973,  0.8357,
         -1.5911,  1.5405],
        [-2.1262,  0.0755,  1.3121,  0.9046,  1.5170, -0.6016, -0.2316,  0.2636,
         -0.6847,  0.3850],
        [-0.8737,  0.7612, -0.3263, -1.7572, -0.1345,  2.8286,  1.3816, -0.5042,
          0.9793, -0.6395],
        [-0.0589, -0.0246,  1.7763,  0.0796,  1.3298, -0.0753,  0.6523, -0.2693,
          0.5196,  0.8447],
        [-0.5601,  2.6222, -3.1765,  1.3449,  0.7379, -1.0763, -0.2941, -0.0827,
         -1.0468,  0.8942],
        [-1.0256,  1.5956,  0.0959,  0.1139,  0.5491,  2.4779,  1.1573,  0.8029,
         -0.7076,  0.3851],
        [ 0.1625,  0.3866, -0.2945, -1.3120, -0.1573,  1.3666,  0.6865, -1.7451,
         -1.0847, -0.9344],
        [-2.1279,  

In [8]:
# Separate 6 channels into 3 groups
m = nn.GroupNorm(3, 6)
# Separate 6 channels into 6 groups (equivalent with InstanceNorm)
m = nn.GroupNorm(6, 6)
# Put all 6 channels into a single group (equivalent with LayerNorm)
m = nn.GroupNorm(1, 6)
# Activating the module
output = m(input)

RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [6] and input of shape [2, 2, 10, 10]

In [37]:
a = torch.rand(1,2,4)
print(a)

tensor([[[0.9862, 0.1829, 0.6722, 0.2753],
         [0.8016, 0.8004, 0.9893, 0.9158]]])


In [38]:
l = nn.Linear(4,3)
l(a)

tensor([[[ 0.3841,  0.5012, -0.0477],
         [ 0.5328,  0.4279,  0.0402]]], grad_fn=<ViewBackward0>)

In [50]:
w = l.state_dict()['weight']
b = l.state_dict()['bias']

In [51]:
b

tensor([-0.3136,  0.0834, -0.3261])

In [52]:
a @ w.T + b

tensor([[[ 0.3841,  0.5012, -0.0477],
         [ 0.5328,  0.4279,  0.0402]]])

In [24]:
w.shape

torch.Size([2, 3])

In [53]:
a = torch.rand(1,5,5)
print(a)

tensor([[[0.4364, 0.8492, 0.0646, 0.2669, 0.1412],
         [0.7550, 0.6535, 0.3296, 0.6113, 0.7643],
         [0.2613, 0.0259, 0.1684, 0.0627, 0.9979],
         [0.0401, 0.1605, 0.0653, 0.4228, 0.0393],
         [0.0858, 0.1712, 0.8225, 0.5533, 0.0159]]])


In [58]:
c = nn.Conv2d(1,3,kernel_size=2)
out = c(a)

In [59]:
print(out)

tensor([[[ 1.0249,  0.6282,  0.4944,  0.6134],
         [ 0.6748,  0.4176,  0.5531,  0.7409],
         [ 0.2202,  0.2945,  0.2690,  0.8083],
         [ 0.2726,  0.3688,  0.7849,  0.4657]],

        [[ 0.0315,  0.2776, -0.0771, -0.1134],
         [ 0.4732,  0.3914,  0.2986,  0.0838],
         [ 0.2075,  0.1391,  0.0672,  0.1864],
         [ 0.1164, -0.1085, -0.1278,  0.2404]],

        [[ 0.5893,  0.3278,  0.5994,  0.5763],
         [ 0.3181,  0.2984,  0.4581,  0.4230],
         [ 0.4196,  0.5320,  0.4823,  0.6318],
         [ 0.5214,  0.5362,  0.6946,  0.4402]]], grad_fn=<SqueezeBackward1>)


In [60]:
w = c.state_dict()['weight']
b = c.state_dict()['bias']

In [61]:
w

tensor([[[[ 0.1511,  0.4729],
          [ 0.4548,  0.1293]]],


        [[[ 0.4069,  0.0822],
          [-0.1747, -0.3856]]],


        [[[-0.3689,  0.0834],
          [ 0.1766,  0.0799]]]])

In [8]:
class Sol:
    def __init__(self,a,b) -> int:
        a = self.x(a,b)
        print(a)
    def x(self,a,b):
        return a*b
Sol(3,5)

15
