### **Import Libraries**

In [37]:
import numpy as np
import pandas as pd
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
# Defining dataset
df=pd.read_csv('wine.csv')
df.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [11]:
df.iloc[:,0]

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64

### **Data Transforms**

'''
Transforms can be applied to PIL images, tensors, ndarrays, or custom data
during creation of the DataSet

complete list of built-in transforms: 
https://pytorch.org/docs/stable/torchvision/transforms.html

#### On Images
---------
CenterCrop, Grayscale, Pad, RandomAffine
RandomCrop, RandomHorizontalFlip, RandomRotation
Resize, Scale

#### On Tensors
----------
LinearTransformation, Normalize, RandomErasing

#### Conversion
----------
ToPILImage: from tensor or ndrarray
ToTensor : from numpy.ndarray or PILImage

#### Generic
-------
Use Lambda 

#### Custom
------
Write own class

#### Compose multiple Transforms
---------------------------
composed = transforms.Compose([Rescale(256),
                               RandomCrop(224)])
'''

### **Defining Dataset**

In [35]:
class WineDataset(Dataset):
    def __init__(self,transforms=None):
        wine_df=pd.read_csv('wine.csv')
        self.n_samples=wine_df.shape[0]
        self.x_data=np.array(wine_df.iloc[:,1:])
        self.y_data=np.array(wine_df.iloc[:,[0]])
        self.transform=transforms
        
    def __getitem__(self,index):
        sample= self.x_data[index],self.y_data[index]
        if self.transform:
            sample=self.transform(sample)
            
        return sample
    
    def __len__(self):
        return self.n_samples
    
    
    
class ToTensor():
    def __call__(self,sample):
        inputs,targets=sample
        return torch.from_numpy(inputs),torch.from_numpy(targets)
    
class MulTransform:
    # multiply inputs with a given factor
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        return inputs, targets

composed=torchvision.transforms.Compose([ToTensor()])
dataset=WineDataset(transforms=composed)

# Getting first sample
sample_one=dataset[0]
print(sample_one)

# Load whole dataset 
dataloader=DataLoader(dataset,
                      batch_size=4,
                      shuffle=True)

# Seeing one random sample
dataiter=iter(dataloader)
data=next(dataiter)
print(data)

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03], dtype=torch.float64), tensor([1]))
[tensor([[1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03],
        [1.3240e+01, 2.5900e+00, 2.8700e+00, 2.1000e+01, 1.1800e+02, 2.8000e+00,
         2.6900e+00, 3.9000e-01, 1.8200e+00, 4.3200e+00, 1.0400e+00, 2.9300e+00,
         7.3500e+02],
        [1.3270e+01, 4.2800e+00, 2.2600e+00, 2.0000e+01, 1.2000e+02, 1.5900e+00,
         6.9000e-01, 4.3000e-01, 1.3500e+00, 1.0200e+01, 5.9000e-01, 1.5600e+00,
         8.3500e+02],
        [1.1610e+01, 1.3500e+00, 2.7000e+00, 2.0000e+01, 9.4000e+01, 2.7400e+00,
         2.9200e+00, 2.9000e-01, 2.4900e+00, 2.6500e+00, 9.6000e-01, 3.2600e+00,
         6.8000e+02]], dtype=torch.float64), tensor([[1],
        [1

In [ ]:
class NeuralNets:
    def __init__(self,n_features,hidden_size,num_classes):
        super(NeuralNets,self).__init__()
        self.n_features=n_features
        self.l1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.l2 = nn.Linear(hidden_size, num_classes) 
        
    def forward(self, x):
        out = self.l1(x)
        out = self.relu(out)
        out = self.l2(out)
        # no activation and no softmax at the end
        return out
        
        
model = NeuralNet(4, hidden_size, 3).to(device)

In [36]:
for i,(features,target) in enumerate(dataloader):
    features=features.to(device)
    target=target.to(device)
    
     # Forward pass
    outputs = model(images)
    loss = criterion(outputs, labels)
        
    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    
    # This helps in updating the weights
    optimizer.step()

In [6]:
import torch
y=torch.randn((2,2,2),dtype=torch.float64)
y

tensor([[[-3.1184,  2.9264],
         [-0.1158, -0.6502]],

        [[-1.2528, -0.5956],
         [-0.1322,  0.5720]]], dtype=torch.float64)

In [7]:
y.double()

tensor([[[-3.1184,  2.9264],
         [-0.1158, -0.6502]],

        [[-1.2528, -0.5956],
         [-0.1322,  0.5720]]], dtype=torch.float64)