### **The self**
1. Class methods must have an extra first parameter in the method definition. We do not give a value for this parameter when we call the method, Python provides it
2. If we have a method that takes no arguments, then we still have to have one argument.
3. This is similar to this pointer in C++ and this reference in Java.

### **The __init__ method** 
The __init__ method is similar to constructors in C++ and Java. It is run as soon as an object of a class is instantiated. The method is useful to do any initialization you want to do with your object. 

Now let us define a class and create some objects using the self and __init__ method

In [1]:
class circle:
    # class attribute
    pi=3.143
    
    #instance attribute
    def __init__(self,radius):
        self.r=radius
        
    def area(self):
        return __class__.pi*self.r*self.r
    
    def perimeter(self):
        return 2*__class__.pi*self.r
    
    
# Object initialisation
circle1=circle(7)


# Accessing class attributes
print("Value of pi is {}".format(circle1.__class__.pi))

print("Radius={}".format(circle1.r))
# Accessing instance attributes
print("Perimeter of circle={}".format(circle1.perimeter())) 
print("Area of circle={}".format(circle1.area())) 
     
        

Value of pi is 3.143
Radius=7
Perimeter of circle=44.001999999999995
Area of circle=154.00699999999998


## Inheritance
Inheritance is the capability of one class to derive or inherit the properties from another class. The class that derives properties is called the derived class or child class and the class from which the properties are being derived is called the base class or parent class. The benefits of inheritance are:
1. It represents real-world relationships well.
1. It provides the reusability of a code. We don’t have to write the same code again and again. Also, it allows us to add more features to a class without modifying it.
1. It is transitive in nature, which means that if class B inherits from another class A, then all the subclasses of B would automatically inherit from class A.


#### **Types of Inheritance** 
**Single Inheritance**:
Single-level inheritance enables a derived class to inherit characteristics from a single-parent class.

**Multilevel Inheritance**:
Multi-level inheritance enables a derived class to inherit properties from an immediate parent class which in turn inherits properties from his parent class.

**Hierarchical Inheritance**:
Hierarchical level inheritance enables more than one derived class to inherit properties from a parent class.

**Multiple Inheritance**:
Multiple level inheritance enables one derived class to inherit properties from more than one base class.

In [5]:
class Sphere(circle):
    def __init__(self, radius):
        super().__init__(radius)

circle2=Sphere(14)
print("Value of pi is {}".format(circle2.__class__.pi))

print("Radius={}".format(circle2.r))

print("Perimeter of circle={}".format(circle2.perimeter())) 
print("Area of circle={}".format(circle2.area())) 


Value of pi is 3.143
Radius=14
Perimeter of circle=88.00399999999999
Area of circle=616.0279999999999


#### **Super**

In [1]:
class Emp():
	def __init__(self, id, name, Add):
		self.id = id
		self.name = name
		self.Add = Add

# Class freelancer inherits EMP
class Freelance(Emp):
	def __init__(self, id, name, Add, Emails):
		super().__init__(id, name, Add)
		self.Emails = Emails

Emp_1 = Freelance(103, "Suraj kr gupta", "Noida" , "KKK@gmails")
print('The ID is:', Emp_1.id)
print('The Name is:', Emp_1.name)
print('The Address is:', Emp_1.Add)
print('The Emails is:', Emp_1.Emails)


The ID is: 103
The Name is: Suraj kr gupta
The Address is: Noida
The Emails is: KKK@gmails


In [20]:
class Mammal():

	def __init__(self, name):
		print(name, "Is a mammal")

class canFly(Mammal):

	def __init__(self, canFly_name):
		print(canFly_name, "cannot fly")

		# Calling Parent class
		# Constructor
		super().__init__(canFly_name)

class canSwim(Mammal):

	def __init__(self, canSwim_name):

		print(canSwim_name, "cannot swim")

		super().__init__(canSwim_name)

class Animal(canSwim,canFly):

	def __init__(self, name):
		super(canSwim,self).__init__(name)

# Driver Code
Carol = Animal("Dog")


Dog cannot fly
Dog Is a mammal


In [10]:
class ParentA:
    def method(self):
        print("Method in ParentA")

class ParentB:
    def method(self):
        print("Method in ParentB")

class Child(ParentA, ParentB):
    def method(self):
        super(ParentB, self).method()

child = Child()
child.method()  # Output: "Method in ParentB"


AttributeError: 'super' object has no attribute 'method'

In [26]:
import numpy as np
x = np.linspace(1,5,5)
x

array([1., 2., 3., 4., 5.])

In [29]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [96]:
import torch
from torch import nn
x = torch.rand(30,4,2)
y = torch.rand(30,4,2)

In [80]:
print(x)
print(y)

tensor([[[0.4015, 0.9569],
         [0.9667, 0.8752]],

        [[0.6048, 0.2045],
         [0.2638, 0.1286]],

        [[0.6970, 0.7786],
         [0.6345, 0.7868]]])
tensor([[[0.6710, 0.6341],
         [0.5419, 0.5410]],

        [[0.6329, 0.5915],
         [0.1012, 0.0753]],

        [[0.1134, 0.9173],
         [0.8617, 0.9105]]])


In [97]:
z = torch.cat((x,y),dim=1)
z.shape

torch.Size([30, 8, 2])

In [102]:
x = torch.rand(2,1,18,18)
conv = nn.Conv2d(1,2,3,1,padding=1)
conv(x).shape

torch.Size([2, 2, 18, 18])