In [1]:
import numpy as np

### **Array Creation Methods**

1. Array
    It is used to create one-dimensional or multidimensional arrays from scratch.

    array(object,dtype==None, * ,copy=True, order='K',subok=False, ndmin=0)

    Important params:

    dtype: desired data type for the resultant array.

    ndim: Specify the minimum number of dimensions for the resultant array.

In [9]:
A=np.array([[2,3,4],[9,0,7]],ndmin=4)
print(A)
print(A.shape)

[[[[2 3 4]
   [9 0 7]]]]
(1, 1, 2, 3)


2. Linspace
    
    Creates an array with evenly spaced float numbers over a specified interval.

    np.linspace(start,stop,num=50,endpoint=True,retstep=False, dtype= None,axis=0)

    Parameters:
    
    num : number of samples generated

In [13]:
B=np.linspace(2,10,num=10)
print(B)

[ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


3. Arange

    np.arange(start,stop,step,dtype=None)

In [14]:
print(np.arange(2,7,2))

[2 4 6]


4. Uniform Samples

    Generate a random sample from a uniform distribution between lower and higher limit values.

    np.uniform(low=0.0,high=1.0,size=None)

In [22]:
print(np.random.uniform(2,10,size=(8,3)))

[[2.79847964 5.74333988 5.1225801 ]
 [2.72063549 3.55097321 3.54267736]
 [7.22874074 7.75969988 5.92129706]
 [3.63547323 8.83416704 4.94346268]
 [5.91333335 7.38899009 2.26123685]
 [4.76111206 5.35818548 5.41215464]
 [3.93723337 7.52964241 2.55421832]
 [3.10537053 7.2092236  7.44709306]]


5. Random.randint
    
    Generate n random integer samples within a range.

    np.random.randint(low,high=None,size=None,dtype=int)

In [32]:
print(np.random.randint(3,10,size=(2,2)))

[[7 7]
 [3 4]]


6. Random.random
   
    Generate n random float samples.

In [24]:
print(np.random.random((3,3)))

[[0.16129487 0.43255032 0.3940224 ]
 [0.8792846  0.53197059 0.56990929]
 [0.09089005 0.73829868 0.99274349]]


7. Array of zeroes, ones and identity

In [29]:
print(np.zeros((2,3),dtype='int'))
print(np.ones((2,3)))
print(np.identity(5))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


8. Array of K random values

    np.full(shape,fill_value,dtype=None)

In [28]:
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

9. Reshape

In [43]:
A=np.random.randint(2,40,size=(2,6))
print(A.reshape(2,2,-1,3))
print(A.reshape(-1))

[[[[26  5 19]]

  [[ 6 26 32]]]


 [[[16 11 20]]

  [[21 22  4]]]]
[26  5 19  6 26 32 16 11 20 21 22  4]


10. Expand Dimensions


In [50]:
arr=np.array([[2,3,4],[9,0,9]])
np.expand_dims(arr,axis=0)

array([[[2, 3, 4],
        [9, 0, 9]]])

11. Squeeze

In [59]:
s=np.array([[1],[2],[3]])
s.squeeze(axis=1)

array([1, 2, 3])

22. argwhere

    Find and return all the indices of non-zero elements.

In [60]:
A = np.array([[1,2],[0,0],[9,8]])
np.argwhere(A)

array([[0, 0],
       [0, 1],
       [2, 0],
       [2, 1]], dtype=int64)

23. argmin and argmax

24. Any

In [85]:
A=np.any([[[False,False],[False,False]],[[True,False],[False,False]]],axis=(0,1))
print(A)

[ True False]


In [83]:
np.any([[[0,0],[0,1]],[[1,0],[0,0]]],axis=0)

array([[ True, False],
       [False,  True]])

In [84]:
np.any([[[0,0],[0,0]]],axis=1)

array([[False, False]])

25. Slicing

In [20]:
s=np.random.randint(3,100,size=(4,2,3))
print(s)
print("First Element:",s[0])         # Selects a particular element
print("Slicing : {}".format(s[0:1]))       # silces the array

[[[50 99 51]
  [86 88 63]]

 [[12 98 30]
  [31 93 43]]

 [[67 11 74]
  [65  4 69]]

 [[70 93  4]
  [ 8 96 13]]]
First Element: [[50 99 51]
 [86 88 63]]
Slicing : [[[50 99 51]
  [86 88 63]]]


In [21]:
s[0:2,[0],[1,2]]

array([[99, 51],
       [98, 30]])