In [1]:
import numpy as np 

In [2]:
x=np.array([[1,2,3],[4,51,7]])
print(x)
print(type(x))
print(x.ndim)

[[ 1  2  3]
 [ 4 51  7]]
<class 'numpy.ndarray'>
2


In [3]:
print(x.shape)

(2, 3)


In [4]:
a1=np.array([1,2,3,4,9,8,7,6,5,4,3,2],ndmin=6)
a2=np.array([1,2,3,4,9,8,7,6,5,4,3,2])
print(a1)
print(a2)

[[[[[[1 2 3 4 9 8 7 6 5 4 3 2]]]]]]
[1 2 3 4 9 8 7 6 5 4 3 2]


In [5]:
a3=a2.reshape(3,4)
print(a3)
print(a2.reshape(2,3,2))

[[1 2 3 4]
 [9 8 7 6]
 [5 4 3 2]]
[[[1 2]
  [3 4]
  [9 8]]

 [[7 6]
  [5 4]
  [3 2]]]


In [6]:
a4=np.array([3,4,5])
print(a4.ndim)
for x in a4:
    print(x,end=' ')

1
3 4 5 

In [7]:
a5=np.array([[3,6,5],[3,7,8]])
for x in a5:
    print(x)

[3 6 5]
[3 7 8]


In [8]:
for x in a5:
    for y in a5:
        print(y)

[3 6 5]
[3 7 8]
[3 6 5]
[3 7 8]


In [9]:
for x in a5:
    for y in x:
        print(y)

3
6
5
3
7
8


In [10]:
x=np.array([1,2,3,4,5])
y=5
print(x+y)
print(x*y)

[ 6  7  8  9 10]
[ 5 10 15 20 25]


In [11]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([0,1,2])
print(x+y)
print(x*y)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
[[ 0  2  6]
 [ 0  5 12]
 [ 0  8 18]]


x=np.array([1,2,3,4,5])
print(x.sum())
print(x.max())
print(x.mean())
print(x.std())
print(np.var(x))

In [12]:
A=np.array([[1, 2], [3, 4]])
print(np.transpose(A))
print(np.trace(A))
print(A.T)

[[1 3]
 [2 4]]
5
[[1 3]
 [2 4]]


In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [14]:
x=np.array([1,2,3,7,90,9])
print(x[:])
print(x[0:4])
print(x[2:])
print(x[:4])
print(x[-4:-1])

[ 1  2  3  7 90  9]
[1 2 3 7]
[ 3  7 90  9]
[1 2 3 7]
[ 3  7 90]


In [15]:
x=np.array([[1,2,3,7,90,9],[1,2,2,17,0,99]])
x[:,np.newaxis,3]
#x[:,np.newaxis,2]

array([[ 7],
       [17]])

In [16]:
print(np.empty(shape=2))
print(np.empty(shape=(2,3)))
print(np.empty(shape=(2,3),dtype=int))

[-2.28028816e-005  4.97669622e+290]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1  2  3]
 [ 7 90  9]]


In [17]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [18]:
print(np.ones(6,dtype=int))
print(np.ones((5,1)))
print(np.ones((5,)))

[1 1 1 1 1 1]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[1. 1. 1. 1. 1.]


In [19]:
print(np.zeros(6,dtype=int))
print(np.zeros((5,1)))
print(np.zeros((5,)))

[0 0 0 0 0 0]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0. 0. 0. 0. 0.]


In [20]:
print(np.full(fill_value=100,shape=7))
print(np.full((3,4),123))

[100 100 100 100 100 100 100]
[[123 123 123 123]
 [123 123 123 123]
 [123 123 123 123]]


In [21]:
x=np.array([[2,3,4,5],[3,78,0,123]])
A=np.asmatrix(x)
print(A)
print(A[0,1])
print(A[1,3])

[[  2   3   4   5]
 [  3  78   0 123]]
3
123


In [22]:
A[0,0]=10000
print(A)

[[10000     3     4     5]
 [    3    78     0   123]]


In [23]:
A=[[2,3,4],[234,567,0]]
print(np.asarray(A))

[[  2   3   4]
 [234 567   0]]


In [37]:
y=np.arange(1,13).reshape((2,6))
print(y)
print(y.diagonal())
print(np.tril(y))
print(np.triu(y))

print(np.trace(y))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[1 8]
[[1 0 0 0 0 0]
 [7 8 0 0 0 0]]
[[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]]
9
