In [2]:
import numpy as np

#### **Array Operations**

In [24]:
x=np.array([[2,3,4],[7,5,0],[8,7,6]])
print(x.min())  # Prints minimum of the whole array
print(np.min(x,axis=0))  # Prints minimum of the along column wise
print(np.min(x,axis=1,keepdims=True))  # Prints minimum of the along row wise

0
[2 3 0]
[[2]
 [0]
 [6]]


14. Unique
    Return an array with all the unique elements sorted.

    np.unique(array,return_index=False,return_inverse=False,return_counts=False,axis=None)

    Important params
    
    return_index: if True, return the indices of the array.
    
    return_inverse: if True, return the indices of the unique array.
    
    return_counts: if True, return the number of times each unique element appears inside the array.
    
    axis: The axis to operate on. By default, the array is considered flattened.

In [15]:
x=np.array([[1,3,4],[1,3,0],[1,3,0],[1,5,4],[1,3,4]])
# Prints the unique values by flatenning the array
print(np.unique(x))

print(np.unique(x,axis=0))
print(np.unique(x,axis=1))

[0 1 3 4 5]
[[1 3 0]
 [1 3 4]
 [1 5 4]]
[[1 3 4]
 [1 3 0]
 [1 3 0]
 [1 5 4]
 [1 3 4]]


15. Mean and median

In [25]:
x=np.array([[1,3,4],[1,3,6],[1,3,0],[1,5,4],[1,3,4]])
print(np.mean(x,axis=1,keepdims=True))

print(np.median(x,axis=0,keepdims=True))

[[2.66666667]
 [3.33333333]
 [1.33333333]
 [3.33333333]
 [2.66666667]]
[[1. 3. 4.]]
