In [1]:
import numpy as np

In [4]:
list=[2,4,5]
asArray=np.array(list) # 1D array
rowVec=np.array([[2,3,4]]) # row Vector
colVec=np.array([[2],[3],[4]]) # column Vector
# print(asArray.shape)

(3,)


##### **Vector Addition in Python**

In [5]:
# Addition same dimentions And orientation vectors
a=np.array([[1],[2],[3]]) # (3,1)
b=np.array([[1],[2],[3]]) # (3,1)
print(a+b)

[[2]
 [4]
 [6]]


In [8]:
# Addition same dimentions And different orientation vectors
a=np.array([[1,2,3]])
b=np.array([[2,3,4]]).T
a+b

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [10]:
# Addition of Scalar and vector
2+np.array([[1,2,3]])


array([[3, 4, 5]])

In [11]:
# Scalar * array
2*np.array([6,4,1])

array([12,  8,  2])

#### **Transpose**

In [13]:
b=np.array([[2,3,4]]).T
b

array([[2],
       [3],
       [4]])

#### **Dot Product**

In [30]:
v = np.array([1,2,3,4])
w = np.array([5,6,7,8])
np.dot(v,w)

70

In [31]:
v.T

array([1, 2, 3, 4])